trigger:
- main

pool: 
    vmImage: ubuntu-test

variables: 
    buildConfigurations: 'Release'
    
steps:
- script: dotnet build --configurtation $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'